#!/usr/bin/env python3
# Commandline control of R&S HM804x PSU over TCP/IP

__author__ = "Mads Meisner-Jensen"
import os
import sys
import argparse
import time
import socket
import re
import enum
import inspect
import serial
from pprint import pprint

PORT_DEFAULT=5025
HOSTNAME_DEFAULT = f"192.168.2.21:{PORT_DEFAULT}"

CMD_DEFAULT = "status"

# Default instrument type to search for with -l option
MDNS_SEARCHFOR_DEFAULT = "HMC804"

# mDNS service type to search for with -l option
MDNS_SERVICE = "_lxi._tcp"


################################################################################
# Simple console colouring (Mads Meisner-Jensen)
################################################################################

import collections

Color = collections.namedtuple('Color', "reset black red green yellow blue magenta cyan white grey ired igreen iyellow iblue imagenta icyan iwhite")
Color.__new__.__defaults__ = ("",) * len(Color._fields)

if sys.stdout.isatty() and os.name != 'nt':
    fg = Color(reset="\033[0m",black="\033[30m",red="\033[31m",green="\033[32m",yellow="\033[33m",blue="\033[34m",magenta="\033[35m",cyan="\033[36m",white="\033[37m",
               grey="\033[90m",ired="\033[91m",igreen="\033[92m",iyellow="\033[93m",iblue="\033[94m",imagenta="\033[95m",icyan="\033[96m",iwhite="\033[97m")
else:
    fg = Color()

class Log(object):
    verbose = 0

    class Level(enum.IntEnum):
        Note = 0
        Info = 1
        Verb = 2
        Debug = 3

    LEVEL_COLOR = [ fg.igreen, fg.icyan, fg.cyan, fg.imagenta ]

    @staticmethod
    def print(level, fmt, *args, **kwargs):
        """bw stands for black and white (no color)"""
        if Log.verbose >= level:
            msg = fmt.format(*args, **kwargs)
            if kwargs.pop('bw', False):
                print(msg)
            else:
                print(Log.LEVEL_COLOR[level] + msg + fg.reset)

    @staticmethod
    def note(fmt, *args, **kwargs):
        Log.print(Log.Level.Note, fmt, *args, **kwargs)

    @staticmethod
    def info(fmt, *args, **kwargs):
        Log.print(Log.Level.Info, fmt, *args, **kwargs)

    @staticmethod
    def verb(fmt, *args, **kwargs):
        Log.print(Log.Level.Verb, fmt, *args, **kwargs)

    @staticmethod
    def debug(fmt, *args, **kwargs):
        Log.print(Log.Level.Debug, fmt, *args, **kwargs)



###############################################################################
# zeroconf (optional dependency)
###############################################################################

try:
    from queue import Queue, Empty as QEmpty
    from zeroconf import ServiceBrowser, Zeroconf, ServiceStateChange

    def mdns_info_get(info):
        addresses = ["%s:%d" % (socket.inet_ntoa(addr), int(info.port)) for addr in info.addresses]
        addresses = ", ".join(addresses)
        props = { k.decode("ascii", errors="ignore"): v.decode("ascii", errors="ignore")
                  for k, v in info.properties.items() }
        return addresses, props

    def mdns_info_tostr(info):
        addresses, props = mdns_info_get(info)
        i = "  " # indent
        props_str = ""
        for k, v in props.items():
            props_str += f"{k}={v} "

        return f"""\
    {i}Address: {addresses}
    {i}Server:  {info.server}
    {i}Props:   {props_str}\
    """

    def string_to_service(s):
        """
        Convert simple service string to correct Zeroconf service string, e.g.

          lxi.tcp -> _lxi._tcp.local.

        :param s:  simple service name, e.g. "http", "ftp, "lxi", "ipp", etc.
                   optionally suffixed by ".tcp" or ".udp"
        :return:   f"_{s}._tcp.local." or f"_{s}._udp.local."
        """
        p = s.split(".")
        # remove the underscores (for easier processing)
        p = [ x.lstrip("_") for x in p ]
        proto = "tcp"
        if len(p) == 2:
            if p[-1] not in ('tcp', 'udp'):
                raise ValueError("Zeroconf service must end with '.tcp' or '.udp'")
            proto = p[-1]
        elif len(p) != 1:
            raise ValueError("Zeroconf service must start with 'SOMENAME.tcp.' or 'SOMENAME.udp'")
        s = f"_{p[0]}._{proto}.local."
        return s


    class ZeroConfHandler(object):
        """
        # Using https://pypi.org/project/zeroconf
        # See also https://www.bountysource.com/teams/python-zeroconf/issues?tracker_ids=3879630

        """
        def __init__(self, service=MDNS_SERVICE):
            self.events = Queue()
            self.service = string_to_service(service)
            self.zeroconf = Zeroconf()
            Log.info("browsing for service: {}", self.service)
            self.browser = ServiceBrowser(self.zeroconf, self.service, handlers=[self.on_event])

        def close(self):
            # Do NOT close: it takes 5 seconds (sic!)
            pass
            #self.zeroconf.close()

        def on_event(self, zeroconf: Zeroconf, service_type: str,
                     name: str, state_change: ServiceStateChange) -> None:
            event = (name, state_change)
            self.events.put(event)

        def get_service_info(self, mdns_type: str, name: str, timeout=None):
            started = time.time()
            info = self.zeroconf.get_service_info(mdns_type, name, timeout=int(1000 * timeout))
            Log.info(f"mDNS get_service_info() elapsed = {time.time() - started:.3f}s")
            return info

    def zeroconf_search(searchfor=None, num=None, timeout=3):
        """

        :param searchfor:
        :param timeout:
        :param num:       Stop when `num` instances have been found
        :return:
        """
        print(searchfor)
        s = "ALL" if not searchfor else searchfor
        Log.info(f"Waiting {timeout:.1f}s for zeroconf events (searchfor={s})...")

        zeroconf = ZeroConfHandler()
        started = time.time()
        last_at = started
        deadline = started + timeout

        found = []
        while time.time() < deadline:
            rem_time = deadline - time.time()
            try:
                ev = zeroconf.events.get(timeout=rem_time)
            except QEmpty:
                continue

            name, ev_type = ev
            if ev_type is ServiceStateChange.Added:
                info = zeroconf.zeroconf.get_service_info(zeroconf.service, name)
                addresses, props = mdns_info_get(info)
                props = [ p for p in props.values()] + [ info.server ]
                all_props = " ".join(props)

                if searchfor is None or searchfor in all_props:
                    if Log.verbose >= Log.Level.Verb:
                        Log.verb(f"Found @ {time.time() - started:.1f}s: {name}")
                    else:
                        print(f"Found {name}")

                    info_str = mdns_info_tostr(info)
                    print(info_str)
                    mdns_ipaddr = socket.inet_ntoa(info.addresses[0])

                    found.append((info.server, mdns_ipaddr))
                    last_at = time.time()
                    if num and len(found) >= num:
                        break

                continue

            elapsed = time.time() - started
            print(f"Found @ {elapsed:.1f}s: {ev_type}, {name}")

            if ev_type is ServiceStateChange.Removed:
                Log.verb(f"Zeroconf Removed: name = {name}")
            elif ev_type is ServiceStateChange.Updated:
                Log.verb(f"Zeroconf Updated: name = {name}")
            else:
                Log.verb(f"Zeroconf OOPS EVENT: name = {name}")

        Log.info("mDNS discovery took {:.1f}s (last result after {:.1f}s), found = \n{}",
                 time.time() - started, last_at - started, "\n".join([str(f) for f in found]))

        return found
except ImportError:
    pass

def zeroconf_add_argument(parser):
    if 'zeroconf' not in sys.modules:
        zero_help = "You need to install Python zeroconf before this works"
    else:
        zero_help = "You seem to have Python zeroconf installed, good"
    parser.add_argument('-l', metavar="STR", dest='zeroconf', type=str,
        nargs='?', const=MDNS_SEARCHFOR_DEFAULT,
        help=f"""Scan for instruments on LAN (using zeroconf {MDNS_SERVICE} service name)
If STR is given then search for that STR in mDNS TXT record
e.g. 'HMC' or the instrument's serial number
Default search STR is '{MDNS_SEARCHFOR_DEFAULT}'.
-ll will list all LXI instruments (empty search/filter string)
{zero_help}""")

def zeroconf_scan(arg):
    if not 'zeroconf' in sys.modules:
        raise RuntimeError("You need to install Python zeroconf")
    searchfor = arg if arg != "l" else ""
    num = None
    if "," in searchfor:
        parts = searchfor.split(",")
        if not (len(parts) == 2 and str.isdigit(parts[0][0])):
            raise RuntimeError(
                "mDNS search NAME format is: [NUM,]NAME where NUM is the number of instances to stop at")
        num, searchfor = int(parts[0]), parts[1]

    devices = zeroconf_search(searchfor, num=num, timeout=5)
    Log.note(f"found {len(devices)} devices")


################################################################################
#
################################################################################

class InstrumentDriver:

    def open(self):
        raise NotImplementedError()

    def close(self):
        raise NotImplementedError()

    def write(self, s):
        raise NotImplementedError()

    def read(self, timeout=None):
        raise NotImplementedError()


class TcpDriver(InstrumentDriver):
    """
    TCP client that uses ASCII protocol with '\n' as message terminator
    """
    def __init__(self, host=None, port=None, flags=0, family=socket.AF_INET):
        super().__init__()
        # Split host into IPADDR and PORT
        if ":" in host:
            host, port = host.rsplit(":", maxsplit=2)
        self.host = host
        self.port = port
        self.flags = flags
        self.family = family
        self.sock = None

    def __str__(self):
        return f"<{self.__class__.__name__}@{self.sock.getpeername()[0]}>"

    def open(self):
        Log.verb(f"TCP connecting to {self.host}:{self.port}")
        for res in socket.getaddrinfo(
                self.host, self.port, self.family, socket.SOCK_STREAM,
                flags=self.flags|socket.AI_CANONNAME):
            af, socktype, proto, canonname, sa = res
            try:
                self.sock = socket.socket(af, socktype, proto)
                self.sock.connect(sa)
                self.sock.settimeout(1)
                Log.verb(f"TCP connected to {self.host} port {self.port} timeout={self.sock.gettimeout()}s")

                # Work-around for HM804x bug where a pending response to the previously
                # connected client is just sent to the next connecting client.
                # Thus we have to start with a flush.
                try:
                    r = self.read(timeout=0.01)
                    if r:
                        print("Flushed HMC804x transmit buffer:", repr(r))
                except socket.timeout:
                    pass
                return

            except OSError as e:
                self.sock.close()
                self.sock = None
                continue

        raise RuntimeError(f"TCP connection to {self.host} port {self.port} failed")

    def close(self):
        self.sock.close()

    def write(self, s):
        Log.info(f"send: {s}")
        self.sock.send(s.encode('ascii') + b"\n")

    def read(self, timeout=None):
        if timeout:
            tout_saved = self.sock.gettimeout()
            self.sock.settimeout(timeout)
        try:
            data = self.sock.recv(1024)
            text = data.decode('ascii').strip()
            Log.info(f"recv: {text}")
            return text
        finally:
            if timeout:
                self.sock.settimeout(tout_saved)


class SerialDriver(InstrumentDriver):
    """
    Serial/VCP (Virtual Com Port) client using ASCII protocol with '\n' as message terminator
    """
    def __init__(self, device=None):
        super().__init__()
        self.device = device
        self.serial = None

    def __str__(self):
        return f"<{self.__class__.__name__}@{self.serial}>"

    def open(self):
        Log.verb(f"{self.__class__.__name__} opening {self.device}")
        try:
            self.serial = serial.Serial(port=self.device, baudrate=115200, exclusive=True, rtscts=True)
        except:
            raise RuntimeError(f"failed to open USB-serial device {self.device}")

    def close(self):
        self.serial.close()

    def write(self, s):
        Log.info(f"send: {s}")
        self.serial.write(s.encode('ascii') + b"\r\n")

    def read(self, timeout=None):
        if timeout:
            tout_saved = self.serial.timeout
            self.serial.timeout = timeout
        try:
            data = self.serial.read_until(size=1024)
            text = data.decode('ascii').strip()
            Log.info(f"recv: {text}")
            return text
        finally:
            if timeout:
                self.serial.timeout = tout_saved


class InstrumentBase:
    def __init__(self, driver):
        self.time_for_queries = 0
        self.driver = driver

    def open(self):
        return self.driver.open()

    def close(self):
        return self.driver.close()

    def write(self, s):
        return self.driver.write(s)

    def read(self, timeout=None):
        return self.driver.read(timeout=timeout)

    def query(self, s):
        started = time.time()
        self.write(s)
        r = self.read()
        elapsed = time.time() - started
        self.time_for_queries += elapsed
        return r

    def opc_wait(self, timeout=1):
        deadline = time.time() + timeout
        while True:
            try:
                self.query("*OPC?")
                break
            except socket.timeout:
                if time.time() >= deadline:
                    raise TimeoutError(f"*OPC? TIMEOUT after {timeout:.1f}s")
                # hmm, what to do?
                time.sleep(0.25)


################################################################################
#
################################################################################

class RohdeSchwarzHMC8043(InstrumentBase):
    """
    R&S®HMC804x Power Supply SCPI Programmers Manual
      https://www.rohde-schwarz.com/us/manual/r-s-hmc804x-power-supply-scpi-programmers-manual-manuals-gb1_78701-172161.html

    R&S®HMC804x Power Supply User Manual
      https://www.rohde-schwarz.com/lv/manual/r-s-hmc804x-power-supply-user-manual-manuals-gb1_78701-78982.html
      https://scdn.rohde-schwarz.com/ur/pws/dl_downloads/dl_common_library/dl_manuals/gb_1/h/hmc804x/HMC804x_UserManual_de_en_04.pdf

    """

    def __init__(self, driver):
        super().__init__(driver)
        self.open()

        self._selected_output = None
        self.id = None
        self._num_chans = None

    def _ask_bool(self, cmd):
        r = self.query(cmd)
        if r == "0":
            return False
        elif r == "1":
            return True
        raise ValueError(f"{self} '{cmd}' returned '{r}' but expected '0' or '1'")

    @property
    def num_chans(self):
        if not self.id:
            self.query_idn()
        return self._num_chans

    def query_idn(self):
        # Rohde&Schwarz,HMC8043,034889436,HW42000000,SW01.400
        self.id = self.query("*IDN?")
        parts = self.id.split(",")
        if parts[1].startswith("HMC804"):
            self._num_chans = int(parts[1][-1])
            Log.verb(f"{parts[1]} has {self._num_chans} outputs/channels")
        else:
            raise EnvironmentError(f"Not a HMC804x instrument? IDN = {self.query_idn}")
        return self.id

    def send_cls(self):
        self.query("*CLS")

    def _assert_chan_current(self, value):
        current_max_per_type = [ 10, 5, 3 ]
        cur_max = current_max_per_type[self.num_chans - 1]
        if value > cur_max:
            raise ValueError(f"Max current for HMC804{self.num_chans} is {cur_max}A (tried {value:.1f}A)")

    def query_system_error(self):
        """
        Responds with `0,"No error"` if there is no error

        :return: errcode, message
        """
        cmd = "SYSTem:ERRor?"
        r = self.query(cmd)
        parts = r.split(",")
        if len(parts) != 2:
            raise RuntimeError(f"Got odd response from {repr(cmd)}: {repr(r)}")
        errcode, msg = parts
        msg = msg.strip('"')
        return int(errcode), msg

    def assert_no_system_error(self):
        err, msg = self.query_system_error()
        if err == 0:
            return
        errmsg = f'{self} returned error: {err},"{msg}"'
        raise RuntimeError(errmsg)

    def select_output(self, index):
        index = int(index)
        if not (1 <= index <= self.num_chans):
            raise ValueError(f"index must be in range [1..{self.num_chans}]")
        if self._selected_output != index:
            self.write(f"INST OUT{index}")
            self._selected_output = index

    def set_voltage(self, index, value):
        self.select_output(index)
        cmd = f"VOLT {value:f}"
        self.write(cmd)
        self.assert_no_system_error()

    def get_voltage(self, index):
        self.select_output(index)
        return float(self.query("VOLT?"))

    def set_current(self, index, value):
        self._assert_chan_current(value)
        self.select_output(index)
        cmd = f"CURR {value:f}"
        self.write(cmd)
        self.assert_no_system_error()

    def get_current(self, index):
        self.select_output(index)
        return float(self.query("CURRent?"))

    def output_enable(self, index, ena):
        """Enable/disable OUTPUT channel, do NOT change MASTER enable"""
        self.select_output(index)
        onoff = "ON" if ena else "OFF"
        cmd = f"OUTPut:CHAN {onoff}"
        self.write(cmd)

    def is_output_enabled(self, index):
        self.select_output(index)
        return self._ask_bool("OUTPut:CHAN?")

    def master_output_enable(self, ena):
        onoff = "ON" if ena else "OFF"
        cmd = f"OUTPUT:MASTER {onoff}"
        self.write(cmd)

    def is_master_output_enabled(self):
        return self._ask_bool("OUTPUT:MASTER?")

    def meas_current(self, index):
        self.select_output(index)
        r = self.query("MEASure:CURRent?")
        if not r:
            Log.verb("MEASure:CURRent? response empty, retrying read")
            r = self.read()
            if not r:
                raise ValueError("MEASure:CURRent? response empty twice!")
        return float(r)

    def meas_voltage(self, index):
        self.select_output(index)
        return float(self.query("MEASure:VOLT?"))

    def print_status(self):
        onoff = "ON" if self.is_master_output_enabled() else "off"
        print(f"Master: {onoff}")
        for i in range(1, self.num_chans + 1):
            onoff = "ON " if self.is_output_enabled(i) else "off"
            print(f"Chan {i}: {onoff} {self.get_voltage(i):6.3f} V {self.get_current(i):6.3f} A  CUR:{self.meas_current(i):6.3f} A")


################################################################################
#
################################################################################

class CmdFuncProxy(object):
    """
    Class that more or less magically turns derived classes into commandline
    classes, i.e. each method that starts with `cmd_` in the derived class
    becomes a command that can be used on the commandline
    """
    def __init__(self, inst):
        self.inst = inst

    cmd_func_args_uppercase = True
    cmd_func_prefix = "cmd_"

    _commands = {}

    @classmethod
    def get_commands(cls):
        """
        Cache all command functions in this class, sorted by lineno.
        The `self.commands` dict will contain all the functions.

        :return:
        """
        if not cls._commands:
            funcs = []
            for name in dir(cls):
                obj = getattr(cls, name)
                if not callable(obj):
                    continue
                if not obj.__name__.startswith(cls.cmd_func_prefix):
                    continue

                funcs.append((obj.__code__.co_firstlineno, obj))

            prefix_len = len(cls.cmd_func_prefix)
            # Make dict of all commands, sorted by lineno
            cls._commands = {
                func.__name__[prefix_len:]: func for lineno, func in sorted(funcs) }

        return cls._commands


    @classmethod
    def iter_syntax_docstr0(cls):
        """
        Iterator that returning (syntax, docstring[0]) for each command

        :return:  cmd_syntax, [ params ], cmd_docstr
        """
        for cmd, func in cls.get_commands().items():
            sig = inspect.signature(func)
            param_names = list(sig.parameters.keys())[1:] # skip `self` param

            syntax = cmd
            params_ltge = [ cmd ]
            if len(param_names):
                for param_name in param_names:
                    syntax_param_name = param_name.upper() if cls.cmd_func_args_uppercase else param_name

                    param = sig.parameters[param_name]
                    if param.default is not inspect.Parameter.empty:
                        syntax_param_name += "=" + str(param.default)
                    params_ltge.append(f"<{syntax_param_name}>")
                syntax += "=" + ",".join(params_ltge[1:])

            docstr0 = inspect.getdoc(func)
            if docstr0:
                docstr0 = docstr0.splitlines()[0]

            yield syntax, params_ltge, docstr0

    def lookup_cmd_by_name(self, name):
        found = []
        for cmd in self.__class__.get_commands():
            if cmd.startswith(name):
                found.append(cmd)
        if len(found) == 1:
            return found[0]
        if len(found) > 1:
            found_str = "', '".join(found)
            raise ValueError(f"Ambiguous command: '{name}' matches '{found_str}'")
        if not found:
            raise ValueError(f"Unknown command: '{name}'")

    def execute(self, cmds):
        for cmd in cmds:
            m = re.match("([a-z_]+)(.*)", cmd)
            if not m:
                raise ValueError(f"Unknown command: {cmd}")

            name = m.group(1)
            allargs = m.group(2)

            name = self.lookup_cmd_by_name(name)

            func = self.__class__.get_commands()[name]
            sig = inspect.signature(func)
            params = sig.parameters
            param_names = list(params.keys())[1:] # skip 'self' param

            num_params_required = 0
            for param_name, param in params.items():
                if param_name == 'self':
                    continue
                param = params[param_name]
                if param.default is inspect.Parameter.empty:
                    num_params_required += 1

            call_args = {}
            args = []
            if allargs:
                args = re.split("=|,|:", allargs)
                if not args[0]:
                    del args[0]

            if len(args) < num_params_required:
                if num_params_required == len(param_names):
                    raise ValueError(f"Expected {len(param_names)} param(s) for '{name}' but got {len(args)}: {args}")
                else:
                    raise ValueError(f"Expected min {num_params_required}, max {len(param_names)} param(s) for '{name}' but got {len(args)}: {args}")
            if len(args) > len(param_names):
                raise ValueError(f"Expected max {len(param_names)} param(s) for '{name}' but got {len(args)}: {args}")

            # Prepare argument dictionary for the method call
            for i, arg in enumerate(args):
                param_name = param_names[i]
                if arg:
                    numerical_arg = float(arg)
                    call_args[param_name] = numerical_arg

            func(self, **call_args)


################################################################################
# PSU Command/Func Proxy
################################################################################

class PSUCmdFuncProxy(CmdFuncProxy):
    """
    When you add new functions to this class they will automatically turn
    into commands for the commandline (it can hardly be much easier).
    """
    cmd_func_prefix = "cmd_"
    cmd_func_args_uppercase = True

    @classmethod
    def iter_syntax_docstr0(cls):
        """Modify the syntax slightly"""
        for syntax, params, docstr in super(PSUCmdFuncProxy, cls).iter_syntax_docstr0():
            if len(params) >= 2 and params[1] == "<CHAN>":
                syntax_mod = "".join(params[:2])
                if len(params) >= 3:
                    syntax_mod += "=" + ",".join(params[2:])
            else:
                syntax_mod = syntax

            yield syntax_mod, docstr

    @staticmethod
    def print_examples():
        print("""\
Set voltage and current of output 1, then show status:
  {prog}  v1=4.1  i1=3  sta
Toggle output 3 off, then on (0.5s delay by default):
  {prog}  tog3
Toggle output 3 off, then on but with 2s delay
  {prog}  off3 wait=2 on3
Show current output of channel 2 
  {prog}  mi2
Measure current of channel 2, report if change is > 3%, 100 reports 
  {prog}  mi2=100,3\
""".format(prog=os.path.basename(__file__)))

    def cmd_on(self, chan):
        """Output channel ON"""
        self.inst.output_enable(chan, 1)

    def cmd_off(self, chan):
        """Output channel OFF"""
        self.inst.output_enable(chan, 0)

    def cmd_toggle(self, chan):
        """Toggle output channel OFF, sleep 0.5s, then ON"""
        self.inst.output_enable(chan, 0)
        self.cmd_wait(0.5)
        self.inst.output_enable(chan, 1)

    def cmd_v(self, chan, VOLTAGE):
        """Set output voltage"""
        self.inst.set_voltage(chan, VOLTAGE)

    def cmd_i(self, chan, CURRENT):
        """Set output maximum current"""
        self.inst.set_current(chan, CURRENT)

    def cmd_master(self, ENABLE):
        """Master ON/OFF"""
        self.inst.master_output_enable(ENABLE)

    def cmd_wait(self, SECONDS):
        """Sleep SECONDS"""
        Log.info(f"wait: {SECONDS:.1f}s")
        time.sleep(SECONDS)

    def cmd_status(self):
        """Print instrument status for all outputs"""
        self.inst.print_status()

    def cmd_mi(self, chan, num=None, d_pct=3, secs=9999, freq=10):
        """Measure output current for some time or number of reports

        :param chan:  Output channel
        :param num:   Number of measurements to report
        :param d_pct: Minimum percentual change before reporting measurement
        :param secs:  Number of seconds to measure
        :param freq:  Frequency of measurements
        :return:
        """
        num_done = 0

        def print_meas():
            dt = now - time_last
            ts_ms = int(1000 * (now - (int(now))))
            ts = f"{time.strftime('%H:%M:%S'):s}.{ts_ms:03d}"
            cur_amps = 1000 * cur
            cur_amps_d = 1000 * cur_d
            print(f"{ts}  {dt:6.3f}s  {cur_amps:5.0f} {cur_amps_d:+5.0f}  {cur_d_pct:3.0f}%")

        msg = ""
        if d_pct > 0:
            msg += f"report if change > {d_pct:.0f}%, "
        if num and num >= 2:
            msg += f"{num:.0f} reports"
            Log.note(f"Measuring current for {secs}s, {msg}")
            print("Time               dt   I/mA dI/mA d/pct")

        now = time.monotonic()
        time_last = now
        cur = self.inst.meas_current(chan)
        cur_last = cur
        cur_d, cur_d_pct = 0, 0
        print_meas()
        num_done += 1

        deadline = time_last + secs
        while num is not None and num_done < num:
            now = time.monotonic()
            if now > deadline:
                break

            cur = self.inst.meas_current(chan)
            cur_d = cur - cur_last

            cur_d_pct = (cur / cur_last - 1) * 100 if cur_last else 100
            if cur_d != 0 and abs(cur_d_pct) >= d_pct:
                print_meas()
                num_done += 1
                cur_last = cur
                time_last = now

            time.sleep(1/freq)


################################################################################
# Main And Argument Parsing
################################################################################

class XDG(object):
    """
    Small python class to get XDG standard directory paths according to the
    XDG Base Directory Specification:
    https://specifications.freedesktop.org/basedir-spec/latest/ar01s02.html
    """
    @staticmethod
    def _path_get(name, default, path=None):
        d = os.environ.get(name, None)
        if not d:
            d = os.path.expanduser(f"~/{default}")
        if path:
            d = os.path.join(d, path)
        return d

    @staticmethod
    def config_home(path=None):
        """
        $XDG_CONFIG_HOME defines the base directory relative to which user
        specific configuration files should be stored. If $XDG_CONFIG_HOME
        is either not set or empty, a default equal to $HOME/.config should be used.
        """
        return XDG._path_get("XDG_CONFIG_HOME", ".config", path)

    @staticmethod
    def config_path():
        filename = os.path.basename(__file__)
        return XDG.config_home(f"{filename}.conf")


def config_read():
    config_path = XDG.config_path()
    if not os.path.isfile(config_path):
        Log.verb(f"Config file '{config_path}' not found")
        return None, None

    Log.verb(f"Reading config file '{config_path}'")
    with open(config_path, "r") as f:
        lines = f.readlines()

    num_lines = 0
    i, phy, device = 0, None, None
    for i, line in enumerate(lines, 1):
        line = line.strip()
        if line.startswith("#") or not line:
            continue
        num_lines += 1

        parts = line.split(" ")
        if not len(parts) == 2:
            raise ValueError(f"""Syntax error at line {i}, expected one of:
tcp IPADDR[:PORT]
ser /dev/serial/by-id/usb-Rohde_Schwarz_HMC8043_VCPxxxxxxxxx-if00
    where IPADDR is the IP address
    and xxxxxxxxx is the ID of the USB serial device
""")
        phy, device = parts

    Log.verb(f"Parsed {num_lines} of {i} lines from config file '{config_path}'")
    return phy, device


def parser_create():
    description = f"""\
Remote control of Rohde & Schwarz HM804x PSU (over TCP/IP or USB-serial/VCP)
Connection method is read from config file at {XDG.config_path()}
"""

    cmds = [ (syntax, doc) for syntax, doc in PSUCmdFuncProxy.iter_syntax_docstr0() ]
    width_max = max([len(syntax) for syntax, doc in cmds])

    cmd_syntaxes = "Commands:\n"
    for syntax, doc in cmds:
        #cmd_syntaxes += "  {:{}s}\n    {}\n".format(syntax, width_max, doc)
        cmd_syntaxes += f"  {syntax}\n      {doc}\n"
    cmd_syntaxes += f"\nCommands can be abbreviated. Default command is: {CMD_DEFAULT}"

    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
        description=description, epilog=cmd_syntaxes, add_help=False)

    parser.add_argument(dest='cmds', metavar='CMD', type=str, nargs='*', default=[CMD_DEFAULT],
        help="One or more commands to execute")

    parser.add_argument('-c', dest='hostandport', metavar="HOST", default="",
        help=f"""TCP Host (and port) to connect to or
USB-serial device to use (e.g. /dev/serial/by-id/usb-Rohde_Schwarz_HMC804x_xxxxxx-if00).
If HOST starts with 'mdns:' the hostname will be looked up using mDNS
(provided that python zeroconf is installed)""")

    zeroconf_add_argument(parser)

    parser.add_argument('-v', dest='verbose', action='count', default=0,
        help="Be more verbose")
    parser.add_argument('-d', dest='debug', action='store_true', default=False,
        help="Show full exception traces on errors")
    parser.add_argument('-h', dest='help', action='count',
        help="Show this help message and exit. Twice to see examples!")

    return parser


def main():
    parser = parser_create()
    opt = parser.parse_args()
    if opt.help:
        if opt.help == 1:
            parser.print_help()
            print(f"(Python {sys.version.split()[0]})")
        elif opt.help == 2:
            PSUCmdFuncProxy.print_examples()
        sys.exit(0)

    Log.verbose = opt.verbose

    try:
        if opt.zeroconf:
            zeroconf_scan(opt.zeroconf)
            sys.exit(0)

        if opt.hostandport.startswith("/dev"):
            driver = SerialDriver(opt.hostandport)
        elif opt.hostandport != "":
            if ":" in opt.hostandport:
                ipaddr, port = opt.hostandport.split(":")
            else:
                ipaddr, port = opt.hostandport, PORT_DEFAULT
                if not ipaddr:
                    ipaddr = HOSTNAME_DEFAULT
            driver = TcpDriver(host=ipaddr, port=port)
        else:
            phy, device = config_read()
            if phy == "tcp":
                driver = TcpDriver(host=device, port=PORT_DEFAULT)
            elif phy == "ser":
                driver = SerialDriver(device)
            else:
                raise RuntimeError("No instrument connection method/interface supplied")

        psu = RohdeSchwarzHMC8043(driver)
        psu_cmdline = PSUCmdFuncProxy(psu)
        psu_cmdline.execute(opt.cmds)

        Log.info(f"{psu.time_for_queries * 1000:.0f}ms")
    except (ValueError, EnvironmentError, RuntimeError) as e:
        if opt.debug:
            raise
        sys.stderr.write(f"ERROR: {e}\n")
        sys.stderr.write("Tip: run with -d option to see full stack trace\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
